spring:
  application:
    name: job-portal-backend
  data:
    mongodb:
      uri: ${DB_STRING:mongodb://localhost:27017/job-portal}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: ${PORT:3000}

jwt:
  secret: M8CcVBFZv8pGo1UFvA3ZSnq+eq7IWTJJcB/fO49H4IA=
  expiration: 86400000

cookie:
  name: ${COOKIE_NAME:jobPortalToken}
  secret: ${COOKIE_SECRET:job-portal-secret-cookie-key-2024}

cors:
  allowed-origins: http://localhost,http://localhost:3000,http://localhost:5173

upload:
  dir: public/uploads/

logging:
  level:
    root: INFO
    com.jobportal: DEBUG
