spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Service Routes
        - id: auth-service
          uri: http://auth-service:3001
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
            - name: JwtValidation

        # User Service Routes
        - id: user-service
          uri: http://user-service:3002
          predicates:
            - Path=/api/v1/users/**,/api/v1/admin/**
          filters:
            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
            - name: JwtValidation

        # Job Service Routes
        - id: job-service
          uri: http://job-service:3003
          predicates:
            - Path=/api/v1/jobs/**
          filters:
            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}

        # Application Service Routes
        - id: application-service
          uri: http://application-service:3004
          predicates:
            - Path=/api/v1/applications/**
          filters:
            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
            - name: JwtValidation

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:M8CcVBFZv8pGo1UFvA3ZSnq+eq7IWTJJcB/fO49H4IA=}

logging:
  level:
    root: INFO
    com.jobportal: DEBUG
